<?php
return array (
  46 => 
  array (
    'id' => '46',
    'catid' => '11',
    'typeid' => '0',
    'title' => '婷儿的小清新',
    'style' => '',
    'thumb' => 'http://aaa.jiemian.com/uploadfile/2016/1214/20161214050534354.jpg',
    'keywords' => '小清新',
    'description' => '来自水瓶座豆瓣女生婷儿的晒家，典型的日式小清新。
日系的装饰，风格素雅，以原木、白色家具为基调，加以棉麻类，装修费用不高，深受大家喜欢，是25岁左右年轻夫妇的理想选择之一。',
    'posids' => '1',
    'url' => 'http://aaa.jiemian.com/index.php?m=content&c=index&a=show&catid=11&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'qishuai',
    'inputtime' => '1481706336',
    'updatetime' => '1481858831',
    'hitsid' => 'c-1-46',
    'views' => '12',
    'yesterdayviews' => '4',
    'dayviews' => '4',
    'weekviews' => '12',
    'monthviews' => '12',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '11',
    'typeid' => '0',
    'title' => '什么是地中海风格',
    'style' => '',
    'thumb' => '',
    'keywords' => '地中海 风格',
    'description' => '    文艺复兴前的西欧，家具艺术经过浩劫与长时期的萧条后，在9至11世纪又重新兴起，并形成独特的风格&mdash;&mdash;地中海式风格。地中海风格家   ',
    'posids' => '0',
    'url' => 'http://aaa.jiemian.com/index.php?m=content&c=index&a=show&catid=11&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482132120',
    'updatetime' => '1482132224',
    'hitsid' => 'c-1-47',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>