<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '16',
    'typeid' => '0',
    'title' => '用心布置简单的家具',
    'style' => '',
    'thumb' => 'http://aaa.jiemian.com/uploadfile/2016/1219/20161219103627715.jpg',
    'keywords' => '家具',
    'description' => '',
    'posids' => '1',
    'url' => 'http://aaa.jiemian.com/index.php?m=content&c=index&a=show&catid=16&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'qishuai',
    'inputtime' => '1482114381',
    'updatetime' => '1482130382',
    'hitsid' => 'c-3-2',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '16',
    'typeid' => '0',
    'title' => '啊啊啊啊',
    'style' => '',
    'thumb' => '',
    'keywords' => '啊啊啊啊',
    'description' => '',
    'posids' => '0',
    'url' => 'http://aaa.jiemian.com/index.php?m=content&c=index&a=show&catid=16&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'qishuai',
    'inputtime' => '1482131761',
    'updatetime' => '1482131761',
    'hitsid' => 'c-3-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '16',
    'typeid' => '0',
    'title' => '啊啊啊啊',
    'style' => '',
    'thumb' => 'http://aaa.jiemian.com/uploadfile/2016/1219/20161219031658607.jpg',
    'keywords' => '啊啊啊啊',
    'description' => '',
    'posids' => '0',
    'url' => 'http://aaa.jiemian.com/index.php?m=content&c=index&a=show&catid=16&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'qishuai',
    'inputtime' => '1482131837',
    'updatetime' => '1482131837',
    'hitsid' => 'c-3-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>